# dsbf/config/default_config.yaml

metadata:
  dataset_name: "titanic"
  dataset_source: "seaborn"
  message_verbosity: debug      # quiet | info | debug
  profiling_depth: full         # basic | standard | full
  output_format: ["md", "json"]
  visualize_dag: true
  layout_name: default

engine:
  engine: ProfileEngine
  backend: polars               # pandas | polars
  reference_dataset_path: null   # default: disabled unless user sets it

  stage_inference:
    null_ratio_raw_threshold: 0.4
    percent_numeric_for_model_ready: 0.7
    high_cardinality_threshold: 50

tasks:
  compare_with_reference_dataset:
    enabled: true
    compare_types: true
    compare_missingness: true
    compare_summary_stats: true
    missing_pct_threshold: 0.3
    unique_count_ratio_threshold: 0.5
    minmax_numeric_tolerance: 0.01

  detect_bimodal_distribution:
    bic_threshold: 10.0

  detect_class_imbalance:
    target_column: target
    imbalance_ratio_threshold: 0.9

  detect_collinear_features:
    vif_threshold: 10.0

  detect_data_leakage:
    correlation_threshold: 0.99

  detect_encoded_columns:
    min_entropy: 4.5               # Minimum entropy to consider a string as possibly encoded
    length_std_threshold: 2.0      # Max allowed std of string lengths (low = suspicious)
    detect_base64: true
    detect_hex: true
    detect_uuid: true

  detect_feature_drift:
    enabled: true
    js_threshold: 0.1
    psi_threshold: 0.1
    ks_pvalue_threshold: 0.05
    tvd_threshold: 0.2
    chi2_pvalue_threshold: 0.05
    # include_visuals: true       # Optional: support for visual output later

  detect_high_cardinality:
    cardinality_threshold: 50

  detect_id_columns:
    threshold_ratio: 0.95

  detect_mixed_type_columns:
    min_ratio: 0.05                # Flag if >5% of values deviate in type
    ignore_null_type: true         # Treat None/NaN as ignorable for mixed type detection

  detect_near_zero_variance:
    threshold: 1e-4               # Flag numeric columns with variance below this value

  detect_out_of_bounds:
    custom_bounds: {
        "age": (0, 120),
        "temperature": (-100, 150),
        "percent": (0, 100),
        "score": (0, 1),
    }

  detect_outliers:
    method: "iqr"
    flag_threshold: 0.01

  detect_regex_format_violations:
    match_threshold: 0.6           # % of values that must match pattern to treat as a structured field
    max_violations: 5              # Max number of invalid examples to display
    custom_patterns: {
      zip: "^\\d{5}(-\\d{4})?$",
      phone: "^\\+?\\d{1,3}?[-.\\s]?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$",
      email: "^[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,}$",
      url: "^https?://[^\\s]+$"
    }

  detect_single_dominant_value:
    dominance_threshold: 0.95

  detect_target_drift:
    enabled: true
    psi_threshold: 0.1
    ks_pvalue_threshold: 0.05
    chi2_pvalue_threshold: 0.05

  detect_zeros:
    flag_threshold: 0.95

  sample_head:
    n: 5

  sample_tail:
    n: 5

  suggest_categorical_encoding:
    low_cardinality_threshold: 10
    high_cardinality_threshold: 50
    correlation_threshold: 0.1
    target_column: target

  suggest_numerical_binning:
    skew_threshold: 1.0

  summarize_nulls:
    null_threshold: 0.5

  summarize_value_counts:
    top_k: 5
