# dsbf/config/default_config.yaml

metadata:
  dataset_name: "titanic"
  dataset_source: "seaborn"
  message_verbosity: debug      # quiet | info | debug
  profiling_depth: full         # basic | standard | full
  output_format: ["md", "json"]
  visualize_dag: true
  layout_name: default

engine:
  engine: ProfileEngine
  backend: polars               # pandas | polars

  stage_inference:
    null_ratio_raw_threshold: 0.4
    percent_numeric_for_model_ready: 0.7
    high_cardinality_threshold: 50

tasks:
  detect_mixed_type_columns:
    min_ratio: 0.05                # Flag if >5% of values deviate in type
    ignore_null_type: true         # Treat None/NaN as ignorable for mixed type detection

  detect_encoded_columns:
    min_entropy: 4.5               # Minimum entropy to consider a string as possibly encoded
    length_std_threshold: 2.0      # Max allowed std of string lengths (low = suspicious)
    detect_base64: true
    detect_hex: true
    detect_uuid: true

  detect_regex_format_violations:
    match_threshold: 0.6           # % of values that must match pattern to treat as a structured field
    sample_limit: 5                # Max number of invalid examples to display
    custom_patterns:
      zip: "^\\d{5}(-\\d{4})?$"
      phone: "^\\+?\\d{1,3}?[-.\\s]?\\(?\\d{3}\\)?[-.\\s]?\\d{3}[-.\\s]?\\d{4}$"
      email: "^[\\w\\.-]+@[\\w\\.-]+\\.\\w{2,}$"
      url: "^https?://[^\\s]+$"
