style: github
template: CHANGELOG.tpl.md
info:
  title: CHANGELOG
  repository_url: https://github.com/W-Thurston/dsbf
options:
  tag_filter_pattern: ^v
  sort_tags:
    method: semver
    order: asc
  commits: null
  commit_groups: null
  header:
    pattern: ^(\w*)\:\s(.*)$
    pattern_maps:
    - Type
    - Subject
  notes:
    keywords:
    - BREAKING CHANGE
  commit_filters:
    exclude:
    - '^Merge '
templates:
  tag: '## {{ .Tag.Name }} - {{ datetime "2006-01-02" .Tag.Date }}'
